"""generate-cards.py — render the <div class="projects"> block of
index.html from projects.yml.

Reads the YAML config, renders each entry as an <article class="project">
following the existing template, and atomically replaces the section
of index.html between the BEGIN/END projects-block markers.

Idempotent: running twice with no projects.yml changes produces no
diff in index.html.

Usage:
    python scripts/generate-cards.py

Reads:    projects.yml
Modifies: index.html (between <!-- BEGIN projects-block --> markers)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
PROJECTS_YML = ROOT / "projects.yml"

BEGIN_MARKER = "<!-- BEGIN projects-block (generated by scripts/generate-cards.py from projects.yml; do not edit) -->"
END_MARKER = "<!-- END projects-block -->"


def render_status(status: str) -> tuple[str, str]:
    """Return (css-class, display-label) for the status pill."""
    if status == "active":
        return ("status--active", "ACTIVE")
    if status == "shipped":
        return ("status--shipped", "SHIPPED")
    if status == "archived":
        return ("status--archived", "ARCHIVED")
    raise ValueError(f"Unknown status: {status}")


def extract_current_meta(html: str, meta_key: str) -> str | None:
    """Return the current text of <span data-meta="{meta_key}"> in index.html.

    The data-meta spans are owned by refresh-meta.py — regenerating the
    cards must not reset a live "last commit: 2d ago" back to the YAML
    placeholder (which would publish a false freshness claim whenever
    the build runs without gh access to the private repos).
    """
    m = re.search(
        r'<span[^>]*data-meta="' + re.escape(meta_key) + r'"[^>]*>([^<]*)</span>',
        html,
    )
    return m.group(1) if m else None


def render_header(project: dict, current_meta: str | None = None) -> str:
    """Render the <header class='project__head'> with status pill and last-commit."""
    status_class, status_label = render_status(project["status"])
    if project.get("auto_meta"):
        # auto_meta=true: render the data-meta sentinel so refresh-meta.py
        # can update the text. Preserve the value already on the page;
        # the YAML placeholder is only for a brand-new card.
        meta_key = project["meta_key"]
        initial_text = (
            current_meta
            or project.get("hardcoded_date")
            or "last commit: n/a"
        )
        last_commit_span = (
            f'<span class="project__last-commit" data-meta="{meta_key}">'
            f"{initial_text}</span>"
        )
    else:
        # auto_meta=false: plain text, no sentinel.
        date_text = project["hardcoded_date"]
        last_commit_span = f'<span class="project__last-commit">{date_text}</span>'
    return (
        '              <header class="project__head">\n'
        f'                <span class="status {status_class}" role="img" aria-label="Status: {status_label.lower()}"></span>\n'
        f'                <span class="project__status-label">{status_label}</span>\n'
        f"                {last_commit_span}\n"
        "              </header>"
    )


def render_name(project: dict) -> str:
    """Render the <h3 class='project__name'>.

    Private repos render as plain text with a "private" pill instead of
    a link — a link to a private repo 404s for any cold visitor, which
    subtracts trust. The pill explains the missing link (the code
    exists, it just isn't public). Public projects with a url link as
    usual; url-less public projects render plain text.
    """
    name = project["name"]
    if project.get("private"):
        return (
            '              <h3 class="project__name">'
            f'{name} <span class="project__private">private</span></h3>'
        )
    url = project.get("url")
    if url:
        return f'              <h3 class="project__name"><a href="{url}" target="_blank" rel="noopener">{name}</a></h3>'
    return f'              <h3 class="project__name">{name}</h3>'


def render_sample(sample: dict | None) -> str | None:
    """Render the <pre class='project__sample'> block, or None if absent.

    tabindex="0": the samples scroll horizontally on narrow viewports
    (overflow-x: auto), and a scrollable region must be reachable by
    keyboard (axe: scrollable-region-focusable, serious).
    """
    if not sample:
        return None
    label = sample["label"]
    html = sample["html"]  # multi-line; literal-block preserves newlines
    return (
        f'              <pre class="project__sample" aria-label="{label}" tabindex="0">{html}</pre>'
    )


def render_media(media: dict | None) -> str | None:
    """Render the <figure class='project__media'> block, or None if absent."""
    if not media:
        return None
    return (
        '              <figure class="project__media">\n'
        f'                <img src="{media["src"]}" alt="{media["alt"]}" '
        f'loading="lazy" decoding="async" '
        f'width="{media["width"]}" height="{media["height"]}" />\n'
        "              </figure>"
    )


def render_cta(cta: dict | None) -> str | None:
    """Render the <p class='project__cta'> block, or None if absent."""
    if not cta:
        return None
    return (
        f'              <p class="project__cta">'
        f'<a class="btn" href="{cta["url"]}" target="_blank" rel="noopener">'
        f'{cta["label"]}</a></p>'
    )


def render_case_study_cta(project: dict) -> str | None:
    """Render a '[ read case study ↓ ]' CTA linking to an on-page case
    study anchor, or None if the project has no case_study.

    For private projects this is the path that survives privacy: the
    card can't link to source, but it can route to the deep writeup.
    The link is a same-page anchor (no target=_blank).
    """
    anchor = project.get("case_study")
    if not anchor:
        return None
    return (
        f'              <p class="project__cta">'
        f'<a class="btn" href="{anchor}">[ read case study &darr; ]</a></p>'
    )


def render_card(project: dict, current_meta: str | None = None) -> str:
    """Render one full <article class='project'> block."""
    parts = [
        '            <article class="project">',
        render_header(project, current_meta),
        render_name(project),
        f'              <p class="project__what">{project["what"]}</p>',
        f'              <p class="project__body">{project["body"]}</p>',
        f'              <p class="project__metrics"><span class="metrics__prefix">//</span> {project["metrics"]}</p>',
        f'              <p class="project__chips">{project["chips"]}</p>',
    ]
    sample = render_sample(project.get("sample"))
    if sample:
        parts.append(sample)
    media = render_media(project.get("media"))
    if media:
        parts.append(media)
    cta = render_cta(project.get("cta"))
    if cta:
        parts.append(cta)
    case_study_cta = render_case_study_cta(project)
    if case_study_cta:
        parts.append(case_study_cta)
    parts.append("            </article>")
    return "\n".join(parts)


def render_projects_block(projects: list[dict], html: str) -> str:
    """Render the full content between BEGIN_MARKER and END_MARKER.

    Order: matches projects.yml. Separated by a blank line between cards.
    """
    cards = []
    for p in projects:
        current = (
            extract_current_meta(html, p["meta_key"])
            if p.get("auto_meta") and p.get("meta_key")
            else None
        )
        cards.append(render_card(p, current))
    return "\n\n".join(cards)


def replace_block(html: str, new_inner: str) -> str:
    """Find the BEGIN/END marker pair and replace the content between them.

    The markers themselves stay; what changes is just the rendered cards.
    """
    begin_idx = html.find(BEGIN_MARKER)
    end_idx = html.find(END_MARKER)
    if begin_idx == -1 or end_idx == -1 or end_idx < begin_idx:
        raise RuntimeError(
            "Could not find BEGIN/END projects-block markers in index.html. "
            "These markers should sit inside <div class=\"projects\">."
        )
    # Everything from begin_idx through the end of the BEGIN_MARKER line
    # is preserved; same for the END_MARKER. We replace what's in between.
    after_begin = begin_idx + len(BEGIN_MARKER)
    before_end = end_idx
    # Use \n separators so the markers stay on their own lines, and the
    # rendered cards start on a fresh line.
    return (
        html[:after_begin]
        + "\n"
        + new_inner
        + "\n"
        + html[before_end:]
    )


def main() -> None:
    projects = yaml.safe_load(PROJECTS_YML.read_text(encoding="utf-8"))
    if not isinstance(projects, list) or not projects:
        raise SystemExit("projects.yml is empty or not a list")

    html = INDEX.read_text(encoding="utf-8")
    new_inner = render_projects_block(projects, html)
    new_html = replace_block(html, new_inner)

    if new_html == html:
        print(f"[same] index.html projects block unchanged ({len(projects)} projects)")
        return

    INDEX.write_text(new_html, encoding="utf-8")
    # Count what changed for a useful log line
    old_card_count = html.count('<article class="project">')
    new_card_count = new_html.count('<article class="project">')
    print(
        f"[ok]   regenerated projects block: "
        f"{old_card_count} -> {new_card_count} cards"
    )


if __name__ == "__main__":
    main()
